# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="graph-fa2"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="ForceAtlas2 pure-elisp background-cached engine"

HOMEPAGE="https://github.com/elij/graph-fa2"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
