# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="synaxis"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Feed reader with SQLite storage"

HOMEPAGE="https://git.thanosapollo.org/synaxis"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/keymap-popup"
RDEPEND="app-emacs/keymap-popup"
