# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="magent"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="AI coding agent"

HOMEPAGE="https://github.com/jamie-cui/magent"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/gptel
	app-emacs/yaml
	app-emacs/compat
	app-emacs/acp
	app-emacs/agent-shell"
RDEPEND="app-emacs/gptel
	app-emacs/yaml
	app-emacs/compat
	app-emacs/acp
	app-emacs/agent-shell"
