# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="magit-gh"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="GitHub CLI integration for Magit"

HOMEPAGE="https://github.com/jonathanchu/magit-gh"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/magit
	app-emacs/transient"
RDEPEND="app-emacs/magit
	app-emacs/transient"
