# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="citar-vulpea"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Minor mode integrating Citar and Vulpea"

HOMEPAGE="https://github.com/fabcontigiani/citar-vulpea"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/citar
	app-emacs/vulpea"
RDEPEND="app-emacs/citar
	app-emacs/vulpea"
