# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="dorgygen"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Source code documentation in org-mode"

HOMEPAGE="https://github.com/drghirlanda/dorgygen"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
