# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="nix3"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Frontend to experimental commands of Nix"

HOMEPAGE="https://github.com/emacs-twist/nix3.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/promise
	app-emacs/compat
	app-emacs/magit-section
	app-emacs/s
	app-emacs/transient"
RDEPEND="app-emacs/promise
	app-emacs/compat
	app-emacs/magit-section
	app-emacs/s
	app-emacs/transient"
