# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="oauth2-request"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="OAuth2 request package interface"

HOMEPAGE="https://melpa.org/packages/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/oauth2
	app-emacs/request"
RDEPEND="app-emacs/oauth2
	app-emacs/request"
