# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="hnview"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Standalone Hacker News client"

HOMEPAGE="https://github.com/luciuschen/hnview"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/llm
	app-emacs/plz"
RDEPEND="app-emacs/llm
	app-emacs/plz"
