# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="gptel-forge-prs"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Generate PR descriptions for forge using gptel"

HOMEPAGE="https://github.com/ArthurHeymans/gptel-forge-prs"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/magit
	app-emacs/forge
	app-emacs/gptel"
RDEPEND="app-emacs/magit
	app-emacs/forge
	app-emacs/gptel"
