# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ob-bigquery"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Babel support for BigQuery -*- lexical-binding: t; -*-x"

HOMEPAGE="https://www.github.com/lhernanz/ob-bigquery"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/org-mode"
RDEPEND="app-emacs/org-mode"
