# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="edit-metadata"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Edit embedded metadata"

HOMEPAGE="https://gitlab.epfl.ch/michael.piotrowski/edit-metadata"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/exiftool
	app-emacs/compat"
RDEPEND="app-emacs/exiftool
	app-emacs/compat"
