# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="llm-test"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="LLM-driven testing for packages"

HOMEPAGE="https://github.com/ahyatt/llm-test"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/llm
	app-emacs/yaml
	app-emacs/futur"
RDEPEND="app-emacs/llm
	app-emacs/yaml
	app-emacs/futur"
