# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="smithers"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A startup message featuring Mr C.M. Burns"

HOMEPAGE="https://melpa.org/packages/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash
	app-emacs/org"
RDEPEND="app-emacs/dash
	app-emacs/org"
