# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ox-leanpub"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Export Org documents to Leanpub book format"

HOMEPAGE="https://melpa.org/packages/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/org
	app-emacs/ox-gfm
	app-emacs/s"
RDEPEND="app-emacs/org
	app-emacs/ox-gfm
	app-emacs/s"
