# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="gnus-browse-url-in-article"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Smarter browse-url for Gnus articles"

HOMEPAGE="https://github.com/jmibanez/gnus-browse-url-in-article"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
