# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="emcp"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Lets your agent talk to Emacs"

HOMEPAGE="https://codeberg.org/martenlienen/emcp"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/http-server
	app-emacs/elisp-refs"
RDEPEND="app-emacs/http-server
	app-emacs/elisp-refs"
