# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="sql-bigquery"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Adds BigQuery support to SQLi mode"

HOMEPAGE="https://github.com/regadas/sql-bigquery"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
