# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-iv"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A tool used to view html generated by org-file immediately (lively)"

HOMEPAGE="https://github.com/kuangdash/org-iv"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/impatient-mode
	app-emacs/org-mode"
RDEPEND="app-emacs/impatient-mode
	app-emacs/org-mode"
